firefly-iii:
  image:
    tag: version-5.7.13
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: firefly.tgarcin.fr
          paths:
            - path: /
              pathType: Prefix
              service:
                name: firefly-iii
                port: 8080
      tls:
        - secretName: firefly.tgarcin.fr-tls
          hosts:
            - firefly.tgarcin.fr
  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi
  redis:
    enabled: true
    replica:
      replicaCount: 0
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi

backups:
  address: 10.0.0.252
  path: "/volume1/Kubernetes/backups/firefly"