firefly-iii:
  image:
    tag: 5.7.10
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: firefly.tgarcin.fr
          paths:
            - path: /
              pathType: Prefix
              service:
                name: firefly-iii
                port: 80
      tls:
        - secretName: firefly.tgarcin.fr-tls
          hosts:
            - firefly.tgarcin.fr
  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi
  redis:
    enabled: true
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi