---
# Source: root/templates/stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/Fall1ngStar/homelab
        revision: main
        directories:
          - path: bootstrap/*
          - path: bootstrap/root
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: 'argocd'
      project: default # TODO
      source:
        repoURL: https://github.com/Fall1ngStar/homelab
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
            - 'secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
---
# Source: root/templates/stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/Fall1ngStar/homelab
        revision: main
        directories:
          - path: system/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default # TODO
      source:
        repoURL: https://github.com/Fall1ngStar/homelab
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
            - 'secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
---
# Source: root/templates/stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/Fall1ngStar/homelab
        revision: main
        directories:
          - path: platform/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default # TODO
      source:
        repoURL: https://github.com/Fall1ngStar/homelab
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
            - 'secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
---
# Source: root/templates/stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/Fall1ngStar/homelab
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default # TODO
      source:
        repoURL: https://github.com/Fall1ngStar/homelab
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
            - 'secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
