apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.252
      share: /volume1/Kubernetes/s3
    volumeHandle: 10.0.0.252#volume1/Kubernetes/s3
  mountOptions:
  - hard
  - nfsvers=4.1
  storageClassName: nfs-csi
