apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  volumeName: {{ .Release.Name }}
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storage.address }}
    path: {{ .Values.storage.path }}
  mountOptions:
    - nfsvers=4.1