{{ if false }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.storage.address }}
    path: {{ .Values.storage.path }}
  mountOptions:
    - nfsvers=4.1
    - hard
{{ end }}