apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-backup-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.backups.address }}
    path: {{ .Values.backups.path }}
  mountOptions:
    - nfsvers=4.1