global:
  appConfig:
    omniauth:
      enabled: true
      allowSingleSignOn: [ "saml" ]
      syncProfileFromProvider: [ "saml" ]
      syncProfileAttributes: [ "email" ]
      autoSignInWithProvider: [ "saml" ]
      blockAutoCreatedUsers: false
      autoLinkSamlUser: true
      providers:
        - name: saml
          args:
            assertion_consumer_service_url:
            idp_cert_fingerprint: 'a5:70:2c:82:c7:c6:02:8a:8c:75:79:98:eb:ea:01:94:10:6c:e5:d7',
            idp_sso_target_url: 'https://auth.tgarcin.fr/application/saml/gitlab/sso/binding/redirect/',
            issuer: 'https://gitlab.tgarcin.fr',
            name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
            attribute_statements:
              email: [ 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress' ],
              first_name: [ 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name' ],
              nickname: [ 'http://schemas.goauthentik.io/2021/02/saml/username' ]
  ingress:
    configureCertmanager: false
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    domain: tgarcin.fr
  edition: ce
  grafana:
    enabled: false

gitlab:
  certmanager:
    installCRDs: false
    install: false
    rbac:
      create: false

  nginx-ingress:
    enabled: false

  gitlab:
    webservice:
      ingress:
        tls:
          secretName: gitlab-tls
    gitaly:
      persistence:
        storageClass: nfs-csi

  registry:
    ingress:
      tls:
        secretName: registry-tls

  minio:
    ingress:
      tls:
        secretName: minio-tls
    persistence:
      storageClass: nfs-csi
  upgradeCheck:
    enabled: false
