global:
  appConfig:
    omniauth:
      enabled: true
      allowSingleSignOn: [ "saml" ]
      syncProfileFromProvider: [ "saml" ]
      syncProfileAttributes: [ "email" ]
      autoSignInWithProvider: [ "saml" ]
      blockAutoCreatedUsers: false
      autoLinkSamlUser: true
      providers:
        - secret: gitlab-saml-provider
          key: provider
  ingress:
    configureCertmanager: false
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    domain: tgarcin.fr
  edition: ce
  grafana:
    enabled: false

saml:
  name: saml
  label: 'saml'
  args:
    assertion_consumer_service_url: 'https://gitlab.tgarcin.fr/users/auth/saml/callback'
    idp_cert_fingerprint: 'a5:70:2c:82:c7:c6:02:8a:8c:75:79:98:eb:ea:01:94:10:6c:e5:d7'
    idp_sso_target_url: 'https://auth.tgarcin.fr/application/saml/gitlab/sso/binding/redirect/'
    issuer: 'https://gitlab.tgarcin.fr'
    name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'

gitlab:
  certmanager:
    installCRDs: false
    install: false
    rbac:
      create: false

  nginx-ingress:
    enabled: false

  gitlab:
    webservice:
      ingress:
        tls:
          secretName: gitlab-tls
    gitaly:
      persistence:
        storageClass: nfs-csi

  registry:
    ingress:
      tls:
        secretName: registry-tls

  minio:
    ingress:
      tls:
        secretName: minio-tls
    persistence:
      storageClass: nfs-csi
  upgradeCheck:
    enabled: false
