minio:
  mode: standalone
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - s3.tgarcin.fr
    tls:
      - secretName: s3-tls-certificate
        hosts:
          - s3.tgarcin.fr
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - s3-console.tgarcin.fr
    tls:
      - secretName: s3-console-tls-certificate
        hosts:
          - s3-console.tgarcin.fr
  resources:
    requests:
      memory: 4Gi
  persistence:
    storageClass: nfs-csi