minio:
  mode: standalone
  ingress:
    apiVersion: networking.k8s.io/v1
    enabled: true
    hosts:
      - s3.tgarcin.fr
    tls:
      - secretName: s3-tls-certificate
        hosts:
          - s3.tgarcin.fr
  metrics:
    serviceMonitor:
      enabled: false